[package]
name = "ddns-client"
version =  { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
ddns-core = { workspace = true , features = ["ddns-client"] }