[package]
name = "ddns-server"
version = "0.1.0"
edition = "2024"

[dependencies]
ddns-core = { workspace = true, features = ["provider-cloudflare"] }
anyhow = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }
base64 = { workspace = true }
argh = { workspace = true }
tonic = { workspace = true }
sqlx = { version = "0.8.6", default-features = false, features = ["sqlite", "macros", "chrono"] }
serde = { version = "1.0.219", features = ["derive"] }
chrono = { workspace = true, features = ["serde"] }
uuid = { version = "1.18.1", features = ["v4", "serde"] }
serde_json = { workspace = true }
hmac = "0.12.1"
sha2 = "0.10.9"
